#!/usr/bin/env python3
"""
Automatically generates a dynamic README.md based on GitHub profile data.
This script fetches your repositories and generates a formatted README.
"""

import requests
import json
from datetime import datetime
from typing import List, Dict, Any
import os

# Configuration
GITHUB_USERNAME = "hollyntt"
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

def get_user_repos() -> List[Dict[str, Any]]:
    """Fetch all repositories for the user."""
    repos = []
    page = 1
    per_page = 100
    
    while True:
        url = f"https://api.github.com/users/{GITHUB_USERNAME}/repos"
        params = {
            "page": page,
            "per_page": per_page,
            "sort": "updated",
            "direction": "desc"
        }
        headers = {}
        if GITHUB_TOKEN:
            headers["Authorization"] = f"token {GITHUB_TOKEN}"
        
        response = requests.get(url, params=params, headers=headers)
        if response.status_code != 200:
            print(f"Error fetching repos: {response.status_code}")
            break
        
        data = response.json()
        if not data:
            break
        
        repos.extend(data)
        page += 1
    
    return repos

def categorize_repos(repos: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Categorize repositories by status and type."""
    categories = {
        "featured": [],
        "active": [],
        "archived": [],
        "forks": []
    }
    
    for repo in repos:
        # Skip if no activity
        if repo["size"] == 0 and repo["open_issues_count"] == 0:
            continue
        
        # Categorize
        if repo["fork"]:
            categories["forks"].append(repo)
        elif repo["archived"]:
            categories["archived"].append(repo)
        elif repo["stargazers_count"] > 0 or repo["forks_count"] > 0:
            categories["featured"].append(repo)
        else:
            categories["active"].append(repo)
    
    return categories

def get_language_stats(repos: List[Dict[str, Any]]) -> Dict[str, int]:
    """Get statistics on languages used."""
    languages = {}
    for repo in repos:
        if repo["language"] and not repo["archived"] and not repo["fork"]:
            languages[repo["language"]] = languages.get(repo["language"], 0) + 1
    return languages

def format_repo_item(repo: Dict[str, Any]) -> str:
    """Format a single repository item."""
    name = repo["name"]
    url = repo["html_url"]
    description = repo["description"] or "No description"
    language = repo["language"] or "Unknown"
    stars = repo["stargazers_count"]
    forks = repo["forks_count"]
    
    item = f"- **[{name}]({url})** - {description}\n"
    item += f"  - Language: {language}"
    
    if stars > 0 or forks > 0:
        item += f" | ⭐ {stars} stars | 🍴 {forks} forks"
    
    if repo["license"]:
        item += f" | License: {repo['license']['name']}"
    
    item += "\n"
    return item

def generate_readme(repos: List[Dict[str, Any]]) -> str:
    """Generate the README content."""
    categories = categorize_repos(repos)
    languages = get_language_stats(repos)
    
    # Sort by stars
    featured = sorted(categories["featured"], key=lambda x: x["stargazers_count"], reverse=True)
    active = sorted(categories["active"], key=lambda x: x["updated_at"], reverse=True)[:5]
    
    readme = f"""# {GITHUB_USERNAME}

Welcome to my GitHub profile! I'm a developer passionate about creating tools and utilities.

**Profile Stats:**
- Total Repositories: {len([r for r in repos if not r['fork']])}
- Total Stars: {sum(r['stargazers_count'] for r in repos if not r['fork'])}
- Total Forks: {sum(r['forks_count'] for r in repos if not r['fork'])}

## 🌟 Featured Projects

"""
    
    if featured:
        for repo in featured[:5]:
            readme += format_repo_item(repo)
    
    readme += f"""
## 💻 Recent Projects

"""
    
    if active:
        for repo in active:
            readme += format_repo_item(repo)
    
    readme += f"""
## 🛠️ Languages & Technologies

"""
    
    if languages:
        for lang, count in sorted(languages.items(), key=lambda x: x[1], reverse=True):
            readme += f"- **{lang}** ({count} projects)\n"
    
    readme += f"""
## 📊 All Repositories

Browse all my repositories on [GitHub](https://github.com/{GITHUB_USERNAME}?tab=repositories).

---

## 🔗 Connect

Feel free to explore, contribute, or reach out!

*Last updated: {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}*
*This README is automatically generated by a Python script.*
"""
    
    return readme

def main():
    """Main function."""
    print("Fetching your repositories...")
    repos = get_user_repos()
    
    if not repos:
        print("Error: No repositories found or GitHub API issue.")
        return
    
    print(f"Found {len(repos)} repositories.")
    print("Generating README...")
    
    readme_content = generate_readme(repos)
    
    # Write to file
    with open("README.md", "w") as f:
        f.write(readme_content)
    
    print("✅ README.md generated successfully!")
    print(f"Total repositories processed: {len(repos)}")

if __name__ == "__main__":
    main()
